cask_args appdir: "/Applications"

tap "railwaycat/emacsmacport"

brew "rbenv"
brew "pyenv"
brew "tree"
brew "svn"
brew "ripgrep"
brew "jq"
brew "jnv"
brew "lesspipe"

cask "iterm2"
cask "docker"
cask "emacs-mac"
cask "karabiner-elements"
